---
name: Test
"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  molecule-test:
    name: "molecule test"
    runs-on: macos-12

    strategy:
      matrix:
        scenario:
          - default
    env:
      PYTHON_VERSION: "3.10"

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: |
            ~/.vagrant.d/boxes
          key: vagrant-boxes-${{ hashFiles('**/Vagrantfile') }}
          restore-keys: |
            vagrant-boxes

      - name: Configure VirtualBox
        run: >-
          sudo mkdir -p /etc/vbox &&
          echo "* 192.168.30.0/24" | sudo tee -a /etc/vbox/networks.conf > /dev/null

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: >-
          python3 -m pip install --upgrade pip &&
          python3 -m pip install -r requirements.txt

      - name: Test with molecule
        run: molecule test --scenario-name ${{ matrix.scenario }}

      - name: Delete old box versions
        if: always() # do this even if a step before has failed
        run: vagrant box prune --force
